name: Haskell CI

on:
  push:
  schedule:
    - cron:  '*/5  * * * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: manual
      tests:
        description: 'Tests'
        required: false
        default: some

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Check event
      run: |
        echo "${{ toJSON(github.event) }}"

    - name: Check event name
      run: |
        echo "${{ github.event_name }}"

    - name: Environment
      run: |
        env | cut -d = -f 1

    - name: Environment
      run: |
        if [ "${{github.event.inputs.tests}}" == "all" ]; then
          echo "Run all tests"
        fi
