name: Nightly trigger

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Invoke workflow with inputs
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Haskell CI
        token: ${{ secrets.MACHINE_TOKEN }}
        inputs: '{ "reason": "nightly", "tests": "all" }'
